### ISSUE TITLE
Make Production Ready

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.activitytypeacl#1]
What would be required to make this extension production-ready?

~~Phase~~ I: Everything Except CiviCase
1. Support Activity ACLS in the following reports:
1.1. Constituent Detail (30m)
1.2. Survey Details (2h)
2. Change filtering of Activities to handle Activities for all Components (30m) 
3. Prevent access to activity pages by direct access by link on unpermissioned pages (1h)
4. Filter the list on Schedule Follow-up Activity dropdown (1h)
5. Update documentation and submit to c.o (1h)
6. Project management including QA (1h)
Total: 7h~~

Phase II: CiviCase
1. Support Activity ACLS in the following reports:
1.1. Case Time Spent (1h)
1.2. Case Detail Report (2h)
2. Adjust Manage Case page:
3.1. Filter list of Activities that can be added (30m)
3.2 Filter activities displayed in case (3-4h)
3.3. Display appropriate view, edit, delete links on each result on case summary tab (3-4h)
3.4. Modify adding timelines so that unpermissioned activities are not added (1h)
3.5 Modify auditing timelines so that unpermissioned activity types are not included in audit (3h or 1h to prevent this kind of audit)
4. Update documentation (.5h)
5. Project management including QA (2h)
Total: 14-18h

**Comment by JoeMurray** [comment]
Monish, could you update this ticket with current status, and perhaps if appropriate revised estimates?

**Comment by monishdeb** [comment]
@JoeMurray here's the status of Phase 1 and 2. 

 Phase I: Everything Except CiviCase

> Support Activity ACLS in the following reports:
> 1.1. Constituent Detail (30m)
> 1.2. Survey Details (2h)
> Change filtering of Activities to handle Activities for all Components (30m)

> Prevent access to activity pages by direct access by link on unpermissioned pages (1h)
> Filter the list on Schedule Follow-up Activity dropdown (1h)
> Update documentation and submit to c.o (1h)
> Project management including QA (1h)
> Total: 7h~~

Not sure. @Edzelopez is this implemented? 


Phase II: CiviCase

> Support Activity ACLS in the following reports:
> 1.1. Case Time Spent (1h)
> 1.2. Case Detail Report (2h)
> Adjust Manage Case page:
> 3.1. Filter list of Activities that can be added (30m)
> 3.2 Filter activities displayed in case (3-4h)
> 3.3. Display appropriate view, edit, delete links on each result on case summary tab (3-4h)
> 3.4. Modify adding timelines so that unpermissioned activities are not added (1h)
> 3.5 Modify auditing timelines so that unpermissioned activity types are not included in audit (3h or 1h to prevent this kind of audit)

done as per this commit https://github.com/JMAConsulting/biz.jmaconsulting.activitytypeacl/commit/a115726884c3b4586ac277ae0ef6166e4d21d912 


> 3. Update documentation (.5h)

Not done. Doc page - https://github.com/JMAConsulting/biz.jmaconsulting.activitytypeacl/wiki/Configuring-Activity-Type-Permissions

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/activitytypeacl/-/issues/1
