### ISSUE TITLE
Incompatible with CiviCase - configuring standard timeline or sequence

### ISSUE THREAD

**Issue by andyburnsco** [JMAConsulting/biz.jmaconsulting.activitytypeacl#12]
When https://github.com/JMAConsulting/biz.jmaconsulting.activitytypeacl is enabled, adding and saving activities underneath the standard timeline, additional timeline or sequence fails to save, see below.

![timeline](https://user-images.githubusercontent.com/18341942/83933790-59535d00-a771-11ea-96da-8842a972ab91.PNG)

![image](https://user-images.githubusercontent.com/18341942/83933825-aa635100-a771-11ea-809e-6cf06657f8b1.png)

This prevents the use of CiviCase as you need at least the Open Case activity on the standard timeline for it to work.

I disabled all WP plugins and extensions. This extension was the culprit. Tested as super admin on WP.

**Comment by seamuslee001** [comment]
Hi @andyburnsco 

I have tested this on a vanilla drupal 7 and wp-demo dev site with org.civicrm.civicase and also this extension enabled. I don't see any obvious issues what permissions were you using?

![activity_type_acl_1](https://user-images.githubusercontent.com/6799125/87755599-a0da0800-c84a-11ea-8670-8089bd8a66cb.jpg)

![activity_type_acl_2](https://user-images.githubusercontent.com/6799125/87755607-a46d8f00-c84a-11ea-8a8d-5073cbc8bd24.jpg)

**Comment by andyburnsco** [comment]
I am on WP. I encountered this as a super admin.

**Comment by Edzelopez** [comment]
I tried this on WP, with superadmin privileges as well. I was able to create activities in the standard timeline, as well as perform normal operations. Any particular errors in the log you can help us out with?

**Comment by sunnycs121** [comment]
I am also seeing this issue on drupal 7. Activities do gets saved on standard timeline, but when you revisit that case type and go under standard timeline tab, they are not there.

**Comment by JoeMurray** [comment]
Hi @sunnycs121 could you confirm if this works when users have the Open Case permission but not if they don't?

**Comment by sunnycs121** [comment]
@JoeMurray I enabled following permissions for administrator role and now seeing 'null' for each activity.

- CiviCRM: add activities of type Open Case
- CiviCRM: view activities of type Open Case
- CiviCRM: edit activities of type Open Case
- CiviCRM: delete activities of type Open Case
![image](https://user-images.githubusercontent.com/2493730/96182604-b28f8200-0f03-11eb-941c-ff0e43193188.png)

**Comment by seamuslee001** [comment]
@sunnycs121 so are you using the CiviCase Extension or just the Component CiviCase?

**Comment by sunnycs121** [comment]
CiviCase component

**Comment by seamuslee001** [comment]
Do you have any other extensions enabled or just this one?

**Comment by sunnycs121** [comment]
We have following other extensions installed:

Summary Fields
Fuzion Tokens
CSV GUI Import to api
Angular Profiles
Contact Layout Editor
FlexMailer
CiviDiscount
Recent Items Menu
CiviCRM Bootstrap theme
Mosaico
Mailgun

**Comment by sunnycs121** [comment]
It started working for me when IF condition in function "toApiOutput" is commented out in file CRM/ActivityTypeACL/APIWrappers/ACL.php

Commented out this condition:
`if ($apiRequest['entity'] == 'CaseType' && $apiRequest['action'] == 'get') {`

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/activitytypeacl/-/issues/12
