### ISSUE TITLE
Edit activity permission requires “EDIT all contacts” permission 

### ISSUE THREAD

**Issue by tapashdatta** [JMAConsulting/biz.jmaconsulting.activitytypeacl#15]
I am not able to give edit activity permission unless the contact has EDIT all contacts permission. Is there fix for this? Thanks

**Comment by Edzelopez** [comment]
Hi @tapashdatta 

Thanks for your report! I'm however a bit confused as to what you are trying to achieve. Could you please clarify what your intentions are with regards to restricting the activities? Maybe provide an explanation by specifying what you did and what you expected this extension to do. I'm here to help :)

**Comment by tapashdatta** [comment]
Hi @Edzelopez I have a group of people who needs to access only certain type of activity like phone call or email. But they not necessarily need to edit the contact or fiddle with group/tags etc. By giving EDIT ALL CONTACT permission allows them to Edit all contacts as well as activities.

**Comment by Edzelopez** [comment]
Thanks for the clarification. I think in this case, you will probably want to make use of [ACLs](https://docs.civicrm.org/user/en/latest/initial-set-up/permissions-and-access-control/) to restrict permissions for contact records. You can then use the ActivityType ACL in combination with that, to allow editing of activities for a particular type when accessed from an activity search. This will allow the activity to be edited, and the ACL will prevent access to the actual contact record. Hope this helps!
