### ISSUE TITLE
Activities appear in summary tab on recent CiviCRM versions

### ISSUE THREAD

**Issue by MegaphoneJon** [JMAConsulting/biz.jmaconsulting.activitytypeacl#2]
In more recent versions of CiviCRM, permissioned activities appear in a contact's activity tab.  You can't view them - clicking "View", "Edit" or "Delete" will result in an error - but you can see information about them in the data table.

I don't know if my client is going to care - I'll ask them.  If you don't hear from me in a week, you can assume we'll continue to use it as is.  I just wanted to make sure you knew in case it affected your clients!

**Comment by MegaphoneJon** [comment]
I did some quick research into this in case I could fix it quickly, and I found that if you change [this line](https://github.com/civicrm/civicrm-core/blob/master/CRM/Activity/BAO/Activity.php#L2902) to use `getActivities()` instead of `deprecatedGetActivities()` the activity tab works as expected.  See https://github.com/civicrm/civicrm-core/pull/12559 and https://github.com/civicrm/civicrm-core/pull/12845.

**Comment by MegaphoneJon** [comment]
Finally - note that Eileen recently committed [that very change](https://github.com/eileenmcnaughton/civicrm-core/commit/40c19fcb00a89f0556e46a8ec28669854d350c2e) to the WMF Civi fork.

I'm going to leave this open in case you feel like tracking this bug, but for my part I'm just going to patch my client's install with Eileen's patch.

**Comment by JoeMurray** [comment]
Core is fixed so no longer necessary. Thanks for noting this here, @MegaphoneJon .

**Comment by francescbassas** [comment]
I am testing this extension because I think it may be interesting for our installations.

I find myself but with the same problem described in this issue _"You can't view them - clicking "View", "Edit" or "Delete" will result in an error - but you can see information about them in the data table."_

I am testing from a version a 5.26.2 CiviCRM where in principle it should be resolved. Any idea where the problem might be?

**Comment by Edzelopez** [comment]
Hi @francescbassas 

I could replicate this on my installation. I'll take a look and have an update for you shortly. Thanks for the report!

**Comment by francescbassas** [comment]
@Edzelopez, were you able to look at it?

**Comment by Edzelopez** [comment]
Yes @francescbassas 
This was quite complicated and turns out it affects quite a few searches, owing to the changes in core. I have submitted a PR here: https://github.com/JMAConsulting/biz.jmaconsulting.activitytypeacl/pull/21 for review.

**Comment by francescbassas** [comment]
@Edzelopez have you made any progress? Just checked #21 and looks like it's stucked.

**Comment by francescbassas** [comment]
> @Edzelopez have you made any progress? Just checked #21 and looks like it's stucked.

just let me know if I can do anything to lend a hand

**Comment by francescbassas** [comment]
Sorry if I get heavy. Just to find out. Is this extension being used by anyone? Is there an intention to keep it? I find it especially interesting for some cases that we are interested in covering in terms of security and user permissions. If necessary I can try to give help to unravel this issue.

**Comment by Edzelopez** [comment]
Hi @francescbassas 

Yes, this extension is currently in production. Apologies for not following up sooner. It looks like my patch worked at one point, but subsequent updates to CiviCRM broke it again. I am currently working out the kinks for this extension for another client of ours and should have this fixed soon.

**Comment by francescbassas** [comment]
Hi @Edzelopez! Just to know if you finally made progress on this issue.

**Comment by lukeyangjma** [comment]
Work in progress PR: https://github.com/JMAConsulting/biz.jmaconsulting.activitytypeacl/pull/26

**Comment by Edzelopez** [comment]
@francescbassas apologies for the delay here. Could you please apply the fixes done in #26 to your instance and let us know ifthe problem is solved? We will then get a new release out. If you do however still have an issue, we would be happy to fix it and get the fix into the current release.

**Comment by monishdeb** [comment]
Moved to https://lab.civicrm.org/extensions/activitytypeacl/-/issues/2
