### ISSUE TITLE
Find contacts and Adv search failure with CiviCRM 5.47.1

### ISSUE THREAD

**Issue by gibsonoliver** [JMAConsulting/biz.jmaconsulting.activitytypeacl#24]
Hi Joe

We have just updated a site to 5.47.1 (D7). 
And the activity type acl extension is bringing up an error when you do a Find Contacts or Adv Search

The error is
Error: Call to undefined method CRM_ActivityTypeACL_BAO_Query::defaultReturnProperties() in CRM_Contact_BAO_Query_Hook->getDefaultReturnProperties() 
(line 158 of /xxxx/drupal7/sites/all/modules/civicrm/CRM/Contact/BAO/Query/Hook.php).

Yours
Olly

**Comment by monishdeb** [comment]
This is a recent regression on 5.47. And @MegaphoneJon submitted a PR https://github.com/JMAConsulting/biz.jmaconsulting.activitytypeacl/pull/23 to fix this issue. The core PR [above](https://github.com/civicrm/civicrm-core/pull/22933) offers a generic solution and soon will be backported to 5.47.x 

@gibsonoliver can you please try this core patch https://github.com/civicrm/civicrm-core/pull/22933 which fixes this issue?

**Comment by gibsonoliver** [comment]
Looks good to me, thank you for getting back so quickly
