### ISSUE TITLE
Activity reports fail when extension is active

### ISSUE THREAD

**Issue by andyburnsco** [JMAConsulting/biz.jmaconsulting.activitytypeacl#3]
We just installed this extension a couple days ago, and now I saw that if the activitytypeacl extension is active, it makes the activity reports fail. Disabling made them work.

Either 
1) We get a WSOD on parent site (character encoding error)
2) On a child site we saw the same issue as this: https://civicrm.stackexchange.com/questions/7897/report-error-bad-menu-record-in-database. Rebuilding the menu did not resolve.

Enabling debugging and error handling does not provide any more errors in UI.

The error log shows: 
```
Apr 11 16:43:09  [info] $Fatal Error Details = Array
(
    [message] => Bad menu record in database
    [code] => 
)


Apr 11 16:43:09  [info] $backTrace = #0 wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(381): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(224): CRM_Core_Error::fatal("Bad menu record in database")
#2 wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:1))
#3 wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#4 wp-content/plugins/civicrm/civicrm.php(1243): CRM_Core_Invoke::invoke((Array:4))
#5 wp-includes/class-wp-hook.php(286): CiviCRM_For_WordPress->invoke("")
#6 wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters("", (Array:1))
#7 wp-includes/plugin.php(465): WP_Hook->do_action((Array:1))
#8 wp-admin/admin.php(253): do_action("toplevel_page_CiviCRM")
#9 {main}
```

On WP 5.1.1 and Civi 5.12 multisite.

**Comment by JoeMurray** [comment]
Thanks for the report, @andyburnsco !

**Comment by Edzelopez** [comment]
@andyburnsco , thanks for this! However, I'm able to use the extension on a couple of instances, and use the activity reports fine (even if the user accessing the reports has no permissioned activities). Could you please tell us more about which report you are getting the error on? Maybe this is WordPress specific, in case, we will check there too.

**Comment by andyburnsco** [comment]
It fails on all activity related reports.

Activity summary, activity detail, Volunteer report and so on. Clicking view results gets WSOD.

**Comment by Edzelopez** [comment]
I managed to replicate this, it was a new issue with the extension using CiviCRM 5.12.3. I have a fix ready, but would like to test conflicts with other reports before pushing the change. Thanks for the report!

**Comment by Edzelopez** [comment]
Hi @andyburnsco ,

Could you please try applying patch from https://github.com/JMAConsulting/biz.jmaconsulting.activitytypeacl/commit/487253a3325049304ed5fa56e79a9fc3e038124b and checking if this resolves the error you were having?

**Comment by andyburnsco** [comment]
I've tested this out and no longer receive any errors. Thanks!

**Comment by Edzelopez** [comment]
You're welcome!
