### ISSUE TITLE
Delete activity type set but does not delete

### ISSUE THREAD

**Issue by andyburnsco** [JMAConsulting/biz.jmaconsulting.activitytypeacl#5]
For a user role I have both _CiviCRM: delete activities of type Phone Call_ and _CiviCRM: Delete activities permissions_.

However, it does not let the user delete the activity type of phone call and says _'You do not have permission to access this page.'_

**Comment by Edzelopez** [comment]
Hi @andyburnsco 

Is the Phone Call activity type a reserved activity type?

**Comment by andyburnsco** [comment]
It is reserved.

**Comment by andyburnsco** [comment]
Any further thoughts on this?

**Comment by seamuslee001** [comment]
Hi @andyburnsco I think reserved activity types cannot be deleted at all. Are you able to provide the url that your trying to access?

**Comment by JoeMurray** [comment]
As this is not meant to override the permission that denies ability to delete reserved activity types, we're closing this issue.

**Comment by JoeMurray** [comment]
As this is not meant to override the permission that denies ability to delete reserved activity types, we're closing this issue.
